Repository jasmar2/codeletter-app, pull requests merged in 2023-03, with the labels that each got.

#53 Modified profile page section
  blog/forms.py
  blog/migrations/0003_alter_profilesettings_profile_image.py
  blog/migrations/0004_alter_profilesettings_profile_image.py
  blog/migrations/0005_alter_profilesettings_profile_image.py
  blog/migrations/0006_rename_profile_image_profilesettings_image.py
  blog/migrations/0007_alter_profilesettings_image.py
  blog/migrations/0008_alter_profilesettings_image.py
  blog/models.py
  blog/static/blog/styles.css
  blog/templates/blog/profile_dashboard.html
  blog/templates/blog/settings_profile.html
  blog/tests/test_user.py
  blog/views/user_view.py
  local/urls.py
  package.json
  templates/base.html
  templates/navbar.html
Labels: enhancement

#54 Modified navbar section
  blog/forms.py
  blog/migrations/0009_rename_linked_in_url_profilesettings_linkedin_url_and_more.py
  blog/models.py
  blog/static/blog/styles.css
  blog/templates/blog/profile_dashboard.html
  blog/templatetags/__init__.py
  blog/templatetags/custom_tags.py
  blog/tests/test_user.py
  templates/navbar.html
Labels: enhancement

#55 Wrote tests for profile settings section
  blog/static/blog/styles.css
  blog/tests/test_user.py
  blog/urls.py
  blog/views/user_view.py
Labels: enhancement

#57 Organized templates in project
  blog/static/blog/styles.css
  blog/templates/blog/category/categories_list.html
  blog/templates/blog/category/category_details.html
  blog/templates/blog/comment/delete_comment.html
  blog/templates/blog/comment/edit_comment.html
  blog/templates/blog/email_message/message_recover_password.html
  blog/templates/blog/email_message/message_verify_account.html
  blog/templates/blog/homepage/homepage.html
  blog/templates/blog/homepage/login_user.html
  blog/templates/blog/homepage/register_user.html
  blog/templates/blog/password/change_password.html
  blog/templates/blog/password/recover_password.html
  blog/templates/blog/password/recover_password_confirm.html
  blog/templates/blog/post/create_post.html
  blog/templates/blog/post/delete_post.html
  blog/templates/blog/post/post_details.html
  blog/templates/blog/user_profile/notifications.html
  blog/templates/blog/user_profile/profile_dashboard.html
  blog/templates/blog/user_profile/settings_profile.html
  blog/templates/blog/user_profile/settings_user.html
  blog/tests/test_comments.py
  blog/tests/test_homepage.py
  blog/tests/test_posts.py
  blog/tests/test_user.py
  blog/views/content_view.py
  blog/views/homepage_view.py
  blog/views/user_view.py
  blog/views/verification_view.py
  package-lock.json
  tailwind.config.js
Labels: refactor

#59 Implemented Markdown + Tailwind Typography
  blog/migrations/0001_initial.py
  blog/migrations/0002_alter_comment_parent.py
  blog/migrations/0003_alter_profilesettings_profile_image.py
  blog/migrations/0004_alter_profilesettings_profile_image.py
  blog/migrations/0005_alter_profilesettings_profile_image.py
  blog/migrations/0006_rename_profile_image_profilesettings_image.py
  blog/migrations/0007_alter_profilesettings_image.py
  blog/migrations/0008_alter_profilesettings_image.py
  blog/migrations/0009_rename_linked_in_url_profilesettings_linkedin_url_and_more.py
  blog/models.py
  blog/static/blog/base.css
  blog/static/blog/styles.css
  blog/templates/blog/homepage/homepage.html
  blog/templates/blog/post/create_post.html
  blog/templates/blog/post/post_details.html
  blog/templates/blog/user_profile/profile_dashboard.html
  blog/templatetags/markdown.py
  blog/views/user_view.py
  local/settings.py
  local/urls.py
  package.json
  requirements.txt
  tailwind.config.js
  templates/base.html
  theme/__init__.py
  theme/apps.py
  theme/static_src/.gitignore
  theme/static_src/package-lock.json
  theme/static_src/package.json
  theme/static_src/postcss.config.js
  theme/static_src/src/styles.css
  theme/static_src/tailwind.config.js
Labels: enhancement

#61 Added table of contents to post details
  blog/templates/blog/post/post_details.html
  blog/views/content_view.py
  templates/base.html
  theme/static_src/tailwind.config.js
Labels: enhancement

#63 Made functional notification system
  blog/templates/blog/post/post_details.html
  blog/templates/blog/user_profile/notifications.html
  blog/templatetags/custom_tags.py
  blog/urls.py
  blog/views/content_view.py
  blog/views/user_view.py
  templates/navbar.html
Labels: enhancement

#65 Added access to view profile dashboard by others
  blog/templates/blog/user_profile/profile_dashboard.html
  blog/tests/test_user.py
  blog/urls.py
  blog/views/user_view.py
  templates/navbar.html
Labels: enhancement

#67 Added styling to create post section
  blog/forms.py
  blog/templates/blog/post/create_post.html
Labels: enhancement

#69 Added styling and logic to homepage
  blog/templates/blog/homepage/homepage.html
  blog/tests/test_homepage.py
  blog/views/homepage_view.py
Labels: enhancement

#71 Added styling to the login page
  blog/templates/blog/homepage/login_user.html
  blog/templates/blog/user_profile/profile_dashboard.html
Labels: enhancement

#73 Added styling to the register page
  blog/forms.py
  blog/templates/blog/homepage/login_user.html
  blog/templates/blog/homepage/register_user.html
Labels: enhancement

#75 Added styling to the user settings page
  blog/forms.py
  blog/templates/blog/post/create_post.html
  blog/templates/blog/user_profile/settings_user.html
Labels: enhancement

#80 Fixed the problem with adding and displaying replies
  blog/static/blog/details.js
  blog/templates/blog/post/post_details.html
  blog/tests/test_comments.py
  blog/views/content_view.py
Labels: bugfix

#81 Added styling to comment form and post information
  blog/forms.py
  blog/static/blog/details.js
  blog/templates/blog/post/post_details.html
  blog/views/content_view.py
Labels: enhancement

#83 Added styling to the profile settings section
  blog/forms.py
  blog/templates/blog/user_profile/settings_profile.html
  blog/tests/test_user.py
Labels: enhancement

#85 Fixed notifications management in comment section
  blog/views/content_view.py
Labels: bugfix

#89 Setup Celery for user registration
  blog/tasks.py
  blog/tests/test_verification.py
  blog/views/verification_view.py
  local/__init__.py
  local/celery.py
  local/settings.py
  requirements.txt
Labels: enhancement
